FROM node:current as build

ARG BACKEND_BASE_URL=http://localhost:8001

ENV NODE_ENV=production
ENV VITE_BACKEND_BASEURL=${BACKEND_BASE_URL}

WORKDIR /app
COPY ./ .
RUN yarn install --production=false
RUN yarn build


FROM nginx:stable as run

RUN rm /etc/nginx/conf.d/default.conf
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]