version: "3.9"
services:
  backend:
    image: peptipedia-backend
    container_name: peptipedia-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.peptipedia-api.rule=Host(`api.peptipedia.cl`)
      - traefik.http.services.peptipedia-api.loadbalancer.server.port=8000
      - traefik.http.routers.peptipedia-api.tls=true
      - traefik.http.routers.peptipedia-api.tls.certresolver=letsencrypt
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
      network: host
    volumes:
      - ./backend/config.ini:/app/config.ini:ro
      - ../peptipedia_storage:/storage:rw
    ports:
      - "8000"
    networks:
      - backend
      - peptipedia
    restart: "always"
  app:
    image: peptipedia-frontend
    container_name: peptipedia-frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.peptipedia.rule=Host(`peptipedia.cl`)
      - traefik.http.services.peptipedia.loadbalancer.server.port=80
      - traefik.http.routers.peptipedia.tls=true
      - traefik.http.routers.peptipedia.tls.certresolver=letsencrypt
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
      network: host
      args:
        - BACKEND_BASE_URL=${BACKEND_BASEURL}
    ports:
      - "80"
    networks:
      - peptipedia
    restart: "always"
  static:
    image: nginx
    container_name: peptipedia-static
    labels:
      - traefik.enable=true
      - traefik.http.routers.peptipedia-static.rule=Host(`static.peptipedia.cl`)
      - traefik.http.services.peptipedia-static.loadbalancer.server.port=80
      - traefik.http.routers.peptipedia-static.tls=true
      - traefik.http.routers.peptipedia-static.tls.certresolver=letsencrypt
    command:
      - /bin/bash
      - -c
      - |
        rm -rf /usr/share/nginx/html/*
        nginx -g 'daemon off;'
    volumes:
      - ./bd/backup_sql.zip:/usr/share/nginx/html/downloads/dump_sql.zip:ro
      - ./bd/dump_fasta.zip:/usr/share/nginx/html/downloads/dump_fasta.zip:ro
      - ./bd/dump_csv.zip:/usr/share/nginx/html/downloads/dump_csv.zip:ro
    ports:
      - "80"
    environment:
      - NGINX_HOST=static.peptipedia.cl
    networks:
      - peptipedia
    restart: "always"
networks:
  backend:
    name: peptipedia-backend
  peptipedia:
    name: peptipedia