version: "3.9"
services:
  backend:
    image: peptipedia-backend
    container_name: peptipedia-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/config.ini:/app/config.ini
      - ./bd/backup_sql.zip:/files/downloads/backup_sql.zip
      - ./bd/dump_fasta.zip:/files/downloads/dump_fasta.zip
      - ./bd/dump_csv.zip:/files/downloads/dump_csv.zip
    ports:
      - "8000"
    networks:
      - backend
      - peptipedia
    restart: "always"
  app:
    image: peptipedia-frontend
    container_name: peptipedia-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
      args:
        - BACKEND_BASEURL=${BACKEND_BASEURL}
    ports:
      - "80"
    networks:
      - peptipedia
networks:
  backend:
    name: peptipedia-backend
  peptipedia:
    name: peptipedia