version: "3.3"
services:
  backend:
    build: ./backend/
    volumes:
      -  ./backend/src/modules:/app/src/modules
      -  ./backend/src/config.ini:/app/src/config.ini
      -  ./backend/src/main.py:/app/src/main.py
      -  ./bd/backup.sql:/files/downloads/backup_sql.zip
      -  ./bd/dump.fasta:/files/downloads/dump_fasta.zip
      -  ./bd/dump_csv.zip:/files/downloads/dump_csv.zip
    ports:
      - "8001:8001"
  app :
    build: ./frontend/
    volumes:
      - ./frontend:/app
    depends_on:
      - "backend"
    ports:
      - "3000:3000"
