version: "3.3"
services:
  backend:
    build: ./backend/
    volumes:
      -  ./backend/src:/app/src
      -  ./bd/backup.sql:/files/downloads/backup_sql.zip
      -  ./bd/dump.fasta:/files/downloads/dump_fasta.zip
      -  ./bd/dump_csv.zip:/files/downloads/dump_csv.zip
    ports:
      - "8001:8001"
    restart: "always"
  app :
    build: ./frontend/
    volumes:
      - ./frontend:/app
    depends_on:
      - "backend"
    ports:
      - "3000:3000"
