version: "3.3"
services:
  backend:
    build: ./backend/
    volumes:
      -  ./backend/src:/app/src
      -  ./bd/backup.sql:/app/src/files/downloads/backup.sql
      -  ./bd/dump.fasta:/app/src/files/downloads/dump.fasta
      -  ./bd/dump_csv.zip:/app/src/files/downloads/dump_csv.zip
    ports:
      - "8001:8001"
  app :
    build: ./app/
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
    depends_on:
      - "backend"
    ports:
      - "3000:3000"