version: "3.3"
services:
  backend:
    build: ./backend/
    volumes:
      -  ./backend/src:/app/src
    ports:
      - "8001:8001"
  app :
    build: ./app/
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
    depends_on:
      - "backend"
    ports:
      - "3000:3000"
  ftp_server:
    image: delfer/alpine-ftp-server
    volumes:
      - ./bd/backup.sql:/ftp/peptipedia/backup.sql
      - ./bd/dump_csv.zip:/ftp/peptipedia/dump_csv.zip
      - ./bd/dump.fasta:/ftp/peptipedia/dump.fasta
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=peptipedia|chapalapachala123