FROM continuumio/miniconda3

#Instalación de programas y librerías necesarias
RUN apt-get update && \
    apt-get -y install --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN conda create --name peptipedia python=3.10
RUN echo "conda activate peptipedia" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]
RUN conda install -c bioconda blast

WORKDIR /files/blastdb
WORKDIR /

# Instalación de dependencias de Python
COPY requirements.txt .
RUN pip install -r requirements.txt
WORKDIR /app

ENV PYTHONPATH=.
ENV BLASTDB=/files/blastdb/

#Ejecución de la api
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "peptipedia", "python", "./peptipedia/main.py"]