FROM python:3.10-slim as base

FROM base as build

ARG DEBIAN_FRONTEND=noninteractive
ARG BLAST_VERSION=2.13.0
ARG HMMER_VERSION=3.3.2
ARG CORES=4

RUN apt-get update && \
	apt-get install --no-install-recommends -y \
	wget curl build-essential cpio procps

WORKDIR /work

# Instalación de BLAST
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLAST_VERSION}/ncbi-blast-${BLAST_VERSION}+-src.tar.gz
RUN tar -xzf ncbi-blast-${BLAST_VERSION}+-src.tar.gz
RUN cd ncbi-blast-${BLAST_VERSION}+-src/c++ && ./configure && make -j ${CORES} && make install

# Instalación de Hmmer
RUN wget http://eddylab.org/software/hmmer/hmmer-${HMMER_VERSION}.tar.gz
RUN tar -xzf hmmer-${HMMER_VERSION}.tar.gz
RUN cd hmmer-${HMMER_VERSION} && ./configure && make -j ${CORES} && make install
RUN make -C hmmer-${HMMER_VERSION}/easel install

# Instalación de PfamScan
RUN wget -T 10 http://ftp.ebi.ac.uk/pub/databases/Pfam/Tools/PfamScan.tar.gz
RUN tar -xzf PfamScan.tar.gz
RUN cp -r PfamScan /usr/local/share
# Seteo de permisos y creación de enlace simbólico a /usr/local/
RUN PFAMSCAN_DIR=/usr/local/share/PfamScan && \
	find ${PFAMSCAN_DIR} -type f -exec chmod 644 {} + && \
	find ${PFAMSCAN_DIR} -type d -exec chmod 755 {} + && \
	ln -s ${PFAMSCAN_DIR}/pfam_scan.pl /usr/local/bin/
# Instalación de dependencias de Perl
RUN cpan Moose && \
	cpan bioperl-1.4 && \
	cpan IPC:Run

# Instalación de dependencias de Python
RUN curl -sSL https://install.python-poetry.org | python3 -
COPY pyproject.toml poetry.lock /src/
WORKDIR /src
RUN /root/.local/bin/poetry export --without-hashes --no-interaction --no-ansi -f requirements.txt -o requirements.txt
RUN pip install -r requirements.txt


FROM base as run

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Actualización de paquetes
RUN apt-get update && apt-get upgrade -y

# Instalación de programas y librerías necesarias
RUN apt-get install -y --no-install-recommends \
	zip pp-popularity-contest \
	libpath-tiny-perl \
	metastudent clustalo && \
	rm -rf /var/lib/apt/lists/*

COPY --from=build /usr/local/ /usr/local/

COPY install_requisites/databases /databases/pfam
WORKDIR /databases/pfam
RUN hmmpress Pfam-A.hmm
COPY install_requisites/blastdb /databases/blastdb

# Variables de entorno
ENV BLASTDB="/databases/blastdb" \
	PFAM_DB="/databases/pfam" \
	PERL5LIB="/usr/local/share/PfamScan:${PERL5LIB}"

COPY ./peptipedia /app/peptipedia
WORKDIR /app

# Ejecución de la api
CMD ["sh","-c", "gunicorn peptipedia.wsgi:app -b 0.0.0.0 -w 4"]
