FROM python:3.10

#Instalación de programas y librerías necesarias
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    libpath-tiny-perl metastudent clustalo zip curl wget pp-popularity-contest && \
    rm -rf /var/lib/apt/lists/*

# Instalación de dependencias de Python
COPY pyproject.toml poetry.lock /src/
RUN curl -sSL https://install.python-poetry.org | python3 -
WORKDIR /src
RUN /root/.local/bin/poetry export --without-hashes --no-interaction --no-ansi -o requirements.txt
RUN pip install -r requirements.txt

WORKDIR /app
COPY ./install_requisites ./install_requisites

#Instalación de Hmmer y Pfamscan
WORKDIR /app/install_requisites/hmmer-3.3.2
RUN chmod +x ./configure
RUN ./configure
RUN make
RUN make install
WORKDIR /app/install_requisites/hmmer-3.3.2/easel
RUN make install

WORKDIR /app/install_requisites/databases
RUN hmmpress Pfam-A.hmm

#Instalación de Blast+ y Swissprot
WORKDIR /app/install_requisites/blast
RUN tar -xvf ncbi-blast-2.13.0+-src.tar.gz

#Instalación librerías bioperl
RUN cpan Moose
RUN cpan bioperl-1.4
RUN cpan IPC:Run

#Variables de entorno
ENV PATH="/app/install_requisites/blast/ncbi-blast-2.12.0+/bin:${PATH}"
ENV BLASTDB="/app/install_requisites/blastdb"

ENV PERL5LIB="/app/install_requisites/PfamScan:${PERL5LIB}"
ENV PATH="/app/install_requisites/PfamScan:${PATH}"

RUN chmod 755 "/app/install_requisites/PfamScan/pfam_scan.pl"

WORKDIR /app

ENV PYTHONPATH=.
#Ejecución de la api
CMD ["python3", "/app/peptipedia/main.py"]