version: "3.9"
services:
  reverse-proxy:
    image: traefik:2.8
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    network_mode: bridge
    networks:
      - peptipedia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    restart: "always"
networks:
  peptipedia:
    name: peptipedia