version: "3.9"
services:
  peptipedia-db:
    image: peptipedia-db
    container_name: peptipedia-db
    build:
      context: .
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c shared_buffers=2GB -c effective_cache_size=3GB -c max_wal_size=4GB
    ports:
      - target: 5432
        protocol: tcp
    networks:
      - backend
    restart: always
networks:
  backend:
    name: peptipedia-backend