version: "3.9"
services:
  peptipedia-db:
    image: peptipedia-db
    build:
      context: .
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always
networks:
  backend:
    name: peptipedia-backend