version: "3.9"
services:
  peptipedia-db:
    image: peptipedia-db
    container_name: peptipedia-db
    build:
      context: .
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - backend
    restart: always
networks:
  backend:
    name: peptipedia-backend