@api = http://170.239.85.191:8001/api

POST {{api}}/alignment/
Content-Type: application/json

{
    "data": ">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD"
}


###

POST {{api}}//delete_file/
Content-Type: application/json

{
    "data": "/static/alignments/71312449048538038272.align"
}

###
POST {{api}}//alignment_file/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.fasta"
Content-Type: text/plain

< ./send_data/pvhl.fasta
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST {{api}}/msa/
Content-Type: application/json

{
    "data":">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-2|VHL_HUMAN Isoform 2 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRVYTLKER\nCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-3|VHL_HUMAN Isoform 3 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYR\nGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPE\nNYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD"
}

###
POST {{api}}//msa_file/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.fasta"
Content-Type: text/plain

< ./send_data/msa.fasta
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST {{api}}/phisicochemical/
Content-Type: application/json

{
    "data": ">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-2|VHL_HUMAN Isoform 2 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRVYTLKER\nCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-3|VHL_HUMAN Isoform 3 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYR\nGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPE\nNYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD",
    "options": {
        "length": 1,
        "molecular_weight": 1,
        "isoelectric_point": 1,
        "charge_density": 1,
        "charge": 1
    }
}
###
POST {{api}}/pfam/
Content-Type: application/json

{
    "data": ">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-2|VHL_HUMAN Isoform 2 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRVYTLKER\nCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-3|VHL_HUMAN Isoform 3 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYR\nGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPE\nNYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD"
}
###
POST {{api}}//gene_ontology/
Content-Type: application/json

{
    "data": ">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-2|VHL_HUMAN Isoform 2 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRVYTLKER\nCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-3|VHL_HUMAN Isoform 3 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYR\nGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPE\nNYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD",
    "options": {
        "molecular_function": 1,
        "biological_process": 1,
        "celular_component": 1
    }
}

###
POST {{api}}/codification/
Content-Type: application/json

{
    "data": ">sp|P40337|VHL_HUMAN von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL PE=1 SV=2\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFR\nDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDI\nVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-2|VHL_HUMAN Isoform 2 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPR\nPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRVYTLKER\nCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD\n>sp|P40337-3|VHL_HUMAN Isoform 3 of von Hippel-Lindau disease tumor suppressor OS=Homo sapiens OX=9606 GN=VHL\nMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYR\nGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPE\nNYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD",
    "options": {
        "one_hot_encoding": 1,
        "phisicochemical_properties": 1,
        "digital_signal_processing": 1
    }
}